# Stage 1: Base
FROM node:22-alpine AS base

# Stage 2: Deps
FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# Stage 3: Builder
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Only NEXT_PUBLIC_ variables need to be present at BUILD time
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG NEXT_PUBLIC_SETUP_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_APP_ENV
ARG ZOHO_MEETING_CLIENT_ID
ARG ZOHO_MEETING_CLIENT_SECRET
ARG ZOHO_MEETING_REDIRECT_URI
ARG ZOHO_MEETING_ACCOUNTS_BASE_URL
ARG ZOHO_MEETING_API_BASE_URL
ARG ZOHO_MEETING_RECORDING_API_BASE_URL
ARG ZOHO_CLIENT_ID
ARG ZOHO_CLIENT_SECRET
ARG ZOHO_REDIRECT_URI
ARG ZOHO_ACCOUNTS_BASE_URL
ARG ZOHO_API_BASE_URL
ARG ZOHO_RECORDING_API_BASE_URL

ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ENV NEXT_PUBLIC_SETUP_KEY=$NEXT_PUBLIC_SETUP_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV

# Increase Node.js memory limit for build and disable telemetry
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# Stage 4: Runner
FROM base AS runner
WORKDIR /app

ARG ZOHO_MEETING_CLIENT_ID
ARG ZOHO_MEETING_CLIENT_SECRET
ARG ZOHO_MEETING_REDIRECT_URI
ARG ZOHO_MEETING_ACCOUNTS_BASE_URL
ARG ZOHO_MEETING_API_BASE_URL
ARG ZOHO_MEETING_RECORDING_API_BASE_URL
ARG ZOHO_CLIENT_ID
ARG ZOHO_CLIENT_SECRET
ARG ZOHO_REDIRECT_URI
ARG ZOHO_ACCOUNTS_BASE_URL
ARG ZOHO_API_BASE_URL
ARG ZOHO_RECORDING_API_BASE_URL

ENV NODE_ENV=production
ENV PORT=3000
ENV ZOHO_MEETING_CLIENT_ID=$ZOHO_MEETING_CLIENT_ID
ENV ZOHO_MEETING_CLIENT_SECRET=$ZOHO_MEETING_CLIENT_SECRET
ENV ZOHO_MEETING_REDIRECT_URI=$ZOHO_MEETING_REDIRECT_URI
ENV ZOHO_MEETING_ACCOUNTS_BASE_URL=$ZOHO_MEETING_ACCOUNTS_BASE_URL
ENV ZOHO_MEETING_API_BASE_URL=$ZOHO_MEETING_API_BASE_URL
ENV ZOHO_MEETING_RECORDING_API_BASE_URL=$ZOHO_MEETING_RECORDING_API_BASE_URL
ENV ZOHO_CLIENT_ID=$ZOHO_CLIENT_ID
ENV ZOHO_CLIENT_SECRET=$ZOHO_CLIENT_SECRET
ENV ZOHO_REDIRECT_URI=$ZOHO_REDIRECT_URI
ENV ZOHO_ACCOUNTS_BASE_URL=$ZOHO_ACCOUNTS_BASE_URL
ENV ZOHO_API_BASE_URL=$ZOHO_API_BASE_URL
ENV ZOHO_RECORDING_API_BASE_URL=$ZOHO_RECORDING_API_BASE_URL

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
